insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'Galaxie', 57.46);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'LS', 76.67);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'Impala', 93.64);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'X5', 19.38);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'Tribeca', 27.29);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'C8 Double 12 S', 15.12);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'Lanos', 3.47);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'Escalade EXT', 90.09);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'),'Panamera', 69.9);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Century', 62.57);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Sunfire', 64.42);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), '944', 89.15);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'XL7', 22.24);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), '3500 Club Coupe', 62.67);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'SL-Class', 29.76);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Quattro', 19.13);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), '3500', 86.92);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Solara', 36.14);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Cutlass Supreme', 52.7);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Hombre', 65.04);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Discovery Series II', 13.46);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'G', 65.46);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Colorado', 28.25);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Camaro', 66.3);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Crown Victoria', 80.63);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'S80', 53.88);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Familia', 54.15);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), '2500 Club Coupe', 60.17);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), 'Vision', 33.6);
insert into producto (id, nombre, precio) values (NEXTVAL('hibernate_sequence'), '300D', 83.81);
